<?php return array (
  'btn' => '#ff981e',
  'btn_text' => '#ffffff',
  'bg_page' => '#ffffff',
  'text_top' => '#ffffff',
  'link_top' => '#000000',
  'bg_top' => '#ffffff',
  'text_head' => '#ffffff',
  'link_head' => '#ffffff',
  'bg_header' => '#ffffff',
  'text' => '#050505',
  'link' => '#ff981e',
  'bg_body' => '#ffffff',
  'text_foot' => '#444444',
  'link_foot' => '#ff981e',
  'bg_footer' => '#ededed',
  'text_bottom' => '#ffffff',
  'link_bottom' => '#ff981e',
  'bg_bottom' => '',
);